# Generated by Django 3.1.3 on 2020-11-26 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('pmid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('pubdate', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('doi', models.CharField(max_length=30)),
                ('subject', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'ordering': ('-pubdate',),
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('first', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20)),
                ('chinese', models.CharField(db_index=True, max_length=3)),
                ('affiliation', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'unique_together': {('name', 'affiliation', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('ifactor', models.FloatField()),
            ],
            options={
                'unique_together': {('name', 'ifactor')},
            },
        ),
        migrations.CreateModel(
            name='Author_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('first', models.CharField(db_index=True, max_length=3, null=True)),
                ('cofirst', models.CharField(db_index=True, max_length=3, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.author')),
            ],
            options={
                'unique_together': {('author', 'article')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(through='articles.Author_Article', to='articles.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.journal'),
        ),
    ]
